#pragma once
void task04For();
void task11For();
void task22For();
void task39For();
bool task4While();
void task10While();
bool task22While();
void task01Series();
bool task10Series();
bool task22Series();
void task30Series();